name = "MasterThesis_BramDuthoo"
authors = ["Bram Duthoo", "Daan Van Hauwermeiren", "Michiel Stock"]
[compat]
julia = "1.10.0"
DrWatson = "2.18.0"
[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
